// Code generated by MockGen. DO NOT EDIT.
// Source: conversation.go
//
// Generated by this command:
//
//	mockgen -source=conversation.go -destination=mock_conversation_repo/conversation.go -package=mock_conversation_repo
//

// Package mock_conversation_repo is a generated GoMock package.
package mock_conversation_repo

import (
	context "context"
	reflect "reflect"

	conversation_entity "github.com/opskat/opskat/internal/model/entity/conversation_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationRepo is a mock of ConversationRepo interface.
type MockConversationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockConversationRepoMockRecorder
	isgomock struct{}
}

// MockConversationRepoMockRecorder is the mock recorder for MockConversationRepo.
type MockConversationRepoMockRecorder struct {
	mock *MockConversationRepo
}

// NewMockConversationRepo creates a new mock instance.
func NewMockConversationRepo(ctrl *gomock.Controller) *MockConversationRepo {
	mock := &MockConversationRepo{ctrl: ctrl}
	mock.recorder = &MockConversationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationRepo) EXPECT() *MockConversationRepoMockRecorder {
	return m.recorder
}

// AppendAt mocks base method.
func (m *MockConversationRepo) AppendAt(ctx context.Context, conversationID int64, sortOrder int, msg *conversation_entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAt", ctx, conversationID, sortOrder, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAt indicates an expected call of AppendAt.
func (mr *MockConversationRepoMockRecorder) AppendAt(ctx, conversationID, sortOrder, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAt", reflect.TypeOf((*MockConversationRepo)(nil).AppendAt), ctx, conversationID, sortOrder, msg)
}

// Create mocks base method.
func (m *MockConversationRepo) Create(ctx context.Context, conv *conversation_entity.Conversation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, conv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConversationRepoMockRecorder) Create(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConversationRepo)(nil).Create), ctx, conv)
}

// Delete mocks base method.
func (m *MockConversationRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConversationRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConversationRepo)(nil).Delete), ctx, id)
}

// DeleteMessages mocks base method.
func (m *MockConversationRepo) DeleteMessages(ctx context.Context, conversationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessages", ctx, conversationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessages indicates an expected call of DeleteMessages.
func (mr *MockConversationRepoMockRecorder) DeleteMessages(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessages", reflect.TypeOf((*MockConversationRepo)(nil).DeleteMessages), ctx, conversationID)
}

// Find mocks base method.
func (m *MockConversationRepo) Find(ctx context.Context, id int64) (*conversation_entity.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*conversation_entity.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockConversationRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockConversationRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockConversationRepo) List(ctx context.Context) ([]*conversation_entity.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*conversation_entity.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConversationRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConversationRepo)(nil).List), ctx)
}

// ListMessages mocks base method.
func (m *MockConversationRepo) ListMessages(ctx context.Context, conversationID int64) ([]*conversation_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, conversationID)
	ret0, _ := ret[0].([]*conversation_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockConversationRepoMockRecorder) ListMessages(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockConversationRepo)(nil).ListMessages), ctx, conversationID)
}

// LoadOrdered mocks base method.
func (m *MockConversationRepo) LoadOrdered(ctx context.Context, conversationID int64) ([]*conversation_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOrdered", ctx, conversationID)
	ret0, _ := ret[0].([]*conversation_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadOrdered indicates an expected call of LoadOrdered.
func (mr *MockConversationRepoMockRecorder) LoadOrdered(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOrdered", reflect.TypeOf((*MockConversationRepo)(nil).LoadOrdered), ctx, conversationID)
}

// TruncateFrom mocks base method.
func (m *MockConversationRepo) TruncateFrom(ctx context.Context, conversationID int64, fromSortOrder int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TruncateFrom", ctx, conversationID, fromSortOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// TruncateFrom indicates an expected call of TruncateFrom.
func (mr *MockConversationRepoMockRecorder) TruncateFrom(ctx, conversationID, fromSortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TruncateFrom", reflect.TypeOf((*MockConversationRepo)(nil).TruncateFrom), ctx, conversationID, fromSortOrder)
}

// Update mocks base method.
func (m *MockConversationRepo) Update(ctx context.Context, conv *conversation_entity.Conversation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConversationRepoMockRecorder) Update(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConversationRepo)(nil).Update), ctx, conv)
}

// UpdateAt mocks base method.
func (m *MockConversationRepo) UpdateAt(ctx context.Context, conversationID int64, sortOrder int, msg *conversation_entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAt", ctx, conversationID, sortOrder, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAt indicates an expected call of UpdateAt.
func (mr *MockConversationRepoMockRecorder) UpdateAt(ctx, conversationID, sortOrder, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAt", reflect.TypeOf((*MockConversationRepo)(nil).UpdateAt), ctx, conversationID, sortOrder, msg)
}

// UpdateState mocks base method.
func (m *MockConversationRepo) UpdateState(ctx context.Context, conversationID int64, threadID, stateValuesJSON string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateState", ctx, conversationID, threadID, stateValuesJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateState indicates an expected call of UpdateState.
func (mr *MockConversationRepoMockRecorder) UpdateState(ctx, conversationID, threadID, stateValuesJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateState", reflect.TypeOf((*MockConversationRepo)(nil).UpdateState), ctx, conversationID, threadID, stateValuesJSON)
}

// UpdateTitle mocks base method.
func (m *MockConversationRepo) UpdateTitle(ctx context.Context, id int64, title string, updatetime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTitle", ctx, id, title, updatetime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTitle indicates an expected call of UpdateTitle.
func (mr *MockConversationRepoMockRecorder) UpdateTitle(ctx, id, title, updatetime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTitle", reflect.TypeOf((*MockConversationRepo)(nil).UpdateTitle), ctx, id, title, updatetime)
}

// UpdateWorkDir mocks base method.
func (m *MockConversationRepo) UpdateWorkDir(ctx context.Context, id int64, workDir string, updatetime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkDir", ctx, id, workDir, updatetime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkDir indicates an expected call of UpdateWorkDir.
func (mr *MockConversationRepoMockRecorder) UpdateWorkDir(ctx, id, workDir, updatetime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkDir", reflect.TypeOf((*MockConversationRepo)(nil).UpdateWorkDir), ctx, id, workDir, updatetime)
}
