import { describe, expect, it } from "vitest";
import { buildExternalEditConflicts, buildExternalEditDocuments } from "../stores/externalEditStore";

describe("buildExternalEditDocuments", () => {
  it("merges sessions that point to the same logical document", () => {
    const documents = buildExternalEditDocuments({
      old: {
        id: "old",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-b",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "a",
        originalSize: 1,
        originalModTime: 1,
        originalEncoding: "utf-8",
        lastLocalSha256: "b",
        dirty: true,
        state: "dirty",
        hidden: false,
        expired: false,
        createdAt: 1,
        updatedAt: 10,
        lastLaunchedAt: 10,
        lastSyncedAt: 1,
      },
      newer: {
        id: "newer",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-c",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "a",
        originalSize: 1,
        originalModTime: 1,
        originalEncoding: "utf-8",
        lastLocalSha256: "b",
        dirty: true,
        state: "dirty",
        hidden: false,
        expired: false,
        createdAt: 1,
        updatedAt: 20,
        lastLaunchedAt: 20,
        lastSyncedAt: 1,
      },
    });

    expect(documents).toHaveLength(1);
    expect(documents[0]?.session.id).toBe("newer");
    expect(documents[0]?.documentKey).toBe("101:/srv/app/demo.txt");
  });

  it("prefers an actionable draft over a stale copy", () => {
    const documents = buildExternalEditDocuments({
      stale: {
        id: "stale",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-b",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "a",
        originalSize: 1,
        originalModTime: 1,
        originalEncoding: "utf-8",
        lastLocalSha256: "b",
        dirty: true,
        state: "stale",
        hidden: false,
        expired: false,
        createdAt: 1,
        updatedAt: 30,
        lastLaunchedAt: 30,
        lastSyncedAt: 1,
      },
      draft: {
        id: "draft",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-c",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "a",
        originalSize: 1,
        originalModTime: 1,
        originalEncoding: "utf-8",
        lastLocalSha256: "b",
        dirty: true,
        state: "conflict",
        hidden: false,
        expired: false,
        createdAt: 1,
        updatedAt: 20,
        lastLaunchedAt: 20,
        lastSyncedAt: 1,
      },
    });

    expect(documents).toHaveLength(1);
    expect(documents[0]?.session.id).toBe("draft");
  });
});

describe("buildExternalEditConflicts", () => {
  it("links the original draft with the latest reread snapshot", () => {
    const conflicts = buildExternalEditConflicts({
      draft: {
        id: "draft",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-b",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "a",
        originalSize: 1,
        originalModTime: 1,
        originalEncoding: "utf-8",
        lastLocalSha256: "b",
        dirty: true,
        state: "conflict",
        hidden: false,
        expired: false,
        createdAt: 1,
        updatedAt: 10,
        lastLaunchedAt: 10,
        lastSyncedAt: 1,
      },
      snapshot: {
        id: "snapshot",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-c",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo-new.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo-new",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "c",
        originalSize: 1,
        originalModTime: 2,
        originalEncoding: "utf-8",
        lastLocalSha256: "c",
        dirty: false,
        state: "clean",
        hidden: false,
        expired: false,
        sourceSessionId: "draft",
        createdAt: 2,
        updatedAt: 20,
        lastLaunchedAt: 20,
        lastSyncedAt: 20,
      },
      stale: {
        id: "stale",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-b",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo-old.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo-old",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "a",
        originalSize: 1,
        originalModTime: 1,
        originalEncoding: "utf-8",
        lastLocalSha256: "b",
        dirty: true,
        state: "stale",
        hidden: false,
        expired: false,
        supersededBySessionId: "snapshot",
        createdAt: 1,
        updatedAt: 30,
        lastLaunchedAt: 30,
        lastSyncedAt: 1,
      },
    });

    expect(conflicts).toHaveLength(1);
    expect(conflicts[0]?.primaryDraft.id).toBe("draft");
    expect(conflicts[0]?.retainedDraft?.id).toBe("stale");
    expect(conflicts[0]?.activeDraft?.id).toBe("snapshot");
    expect(conflicts[0]?.latestSnapshot?.id).toBe("snapshot");
  });

  it("keeps retained-only reread documents out of the conflict view", () => {
    const conflicts = buildExternalEditConflicts({
      retained: {
        id: "retained",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-b",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo-old.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo-old",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "a",
        originalSize: 1,
        originalModTime: 1,
        originalEncoding: "utf-8",
        lastLocalSha256: "b",
        dirty: true,
        state: "stale",
        hidden: false,
        expired: false,
        supersededBySessionId: "active",
        createdAt: 1,
        updatedAt: 30,
        lastLaunchedAt: 30,
        lastSyncedAt: 1,
      },
      active: {
        id: "active",
        assetId: 101,
        assetName: "asset-101",
        documentKey: "101:/srv/app/demo.txt",
        sessionId: "ssh-c",
        remotePath: "/srv/app/demo.txt",
        remoteRealPath: "/srv/app/demo.txt",
        localPath: "/tmp/demo-new.txt",
        workspaceRoot: "/tmp",
        workspaceDir: "/tmp/demo-new",
        editorId: "system-text",
        editorName: "System Text Editor",
        editorPath: "/bin/editor",
        originalSha256: "c",
        originalSize: 1,
        originalModTime: 2,
        originalEncoding: "utf-8",
        lastLocalSha256: "d",
        dirty: true,
        state: "dirty",
        hidden: false,
        expired: false,
        sourceSessionId: "retained",
        createdAt: 2,
        updatedAt: 40,
        lastLaunchedAt: 40,
        lastSyncedAt: 20,
      },
    });

    expect(conflicts).toHaveLength(0);
  });
});
