// Code generated by MockGen. DO NOT EDIT.
// Source: local_tool_grant.go
//
// Generated by this command:
//
//	mockgen -source=local_tool_grant.go -destination=mock_local_tool_grant_repo/local_tool_grant.go -package=mock_local_tool_grant_repo
//

// Package mock_local_tool_grant_repo is a generated GoMock package.
package mock_local_tool_grant_repo

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalToolGrantRepo is a mock of LocalToolGrantRepo interface.
type MockLocalToolGrantRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLocalToolGrantRepoMockRecorder
	isgomock struct{}
}

// MockLocalToolGrantRepoMockRecorder is the mock recorder for MockLocalToolGrantRepo.
type MockLocalToolGrantRepoMockRecorder struct {
	mock *MockLocalToolGrantRepo
}

// NewMockLocalToolGrantRepo creates a new mock instance.
func NewMockLocalToolGrantRepo(ctrl *gomock.Controller) *MockLocalToolGrantRepo {
	mock := &MockLocalToolGrantRepo{ctrl: ctrl}
	mock.recorder = &MockLocalToolGrantRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalToolGrantRepo) EXPECT() *MockLocalToolGrantRepoMockRecorder {
	return m.recorder
}

// Has mocks base method.
func (m *MockLocalToolGrantRepo) Has(ctx context.Context, sessionID, toolName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", ctx, sessionID, toolName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockLocalToolGrantRepoMockRecorder) Has(ctx, sessionID, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockLocalToolGrantRepo)(nil).Has), ctx, sessionID, toolName)
}

// ListBySession mocks base method.
func (m *MockLocalToolGrantRepo) ListBySession(ctx context.Context, sessionID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySession", ctx, sessionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySession indicates an expected call of ListBySession.
func (mr *MockLocalToolGrantRepoMockRecorder) ListBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySession", reflect.TypeOf((*MockLocalToolGrantRepo)(nil).ListBySession), ctx, sessionID)
}

// Save mocks base method.
func (m *MockLocalToolGrantRepo) Save(ctx context.Context, sessionID, toolName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, sessionID, toolName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLocalToolGrantRepoMockRecorder) Save(ctx, sessionID, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLocalToolGrantRepo)(nil).Save), ctx, sessionID, toolName)
}
