package ai

import "github.com/cago-frame/agents/tool"

// assetCagoTools 资产 + 分组的 8 个工具。
// 工具的 Description/Schema 与 AllToolDefs() 中的同名条目保持一致——这是给模型看的契约，不要随意改。
func assetCagoTools() []tool.Tool {
	return []tool.Tool{
		rawTool(
			"list_assets",
			"List managed remote server assets. Returns an array of assets (with ID, name, type, group, etc.). This is typically the first step to discover asset IDs for other operations. Supports filtering by type and group. Use get_asset to view asset description and connection details.",
			makeSchema(
				paramSpec{name: "asset_type", typ: "string", desc: `Filter by asset type. Supported: "ssh", "database", "redis", "mongodb", "kafka", "k8s". Omit to return all types.`},
				paramSpec{name: "group_id", typ: "number", desc: "Filter by group ID. Omit or set to 0 to list all groups."},
			),
			false,
			handleListAssets,
		),
		rawTool(
			"get_asset",
			"Get detailed information about a specific asset, including SSH connection fields and asset-type-specific metadata. For k8s assets, inspect namespace, context, and ssh_tunnel_id to decide whether kubectl should run through an SSH jump host.",
			makeSchema(
				paramSpec{name: "id", typ: "number", required: true, desc: "Asset ID. Use list_assets to find available IDs."},
			),
			false,
			handleGetAsset,
		),
		rawTool(
			"add_asset",
			`Add a new asset to the inventory. Supports types: "ssh", "database", "redis", "mongodb", "kafka", "k8s". For database, specify driver ("mysql" or "postgresql"). For k8s, specify kubeconfig. For kafka, specify brokers (comma-separated) plus optional sasl_mechanism / tls. Credentials (password / private_key) are stored encrypted; never echo them back to the user.`,
			makeSchema(
				paramSpec{name: "name", typ: "string", required: true, desc: "Display name for the asset."},
				paramSpec{name: "type", typ: "string", desc: `Asset type: "ssh" (default), "database", "redis", "mongodb", "kafka", or "k8s".`},
				paramSpec{name: "host", typ: "string", desc: "Hostname or IP address. Required except for k8s and kafka (kafka uses brokers, but host+port falls back to a single broker)."},
				paramSpec{name: "port", typ: "number", desc: "Port number (default: 22 for SSH, 3306 for MySQL, 5432 for PostgreSQL, 6379 for Redis, 27017 for MongoDB, 9092 for Kafka). Required except for k8s; for kafka, used only when brokers is omitted."},
				paramSpec{name: "username", typ: "string", desc: "Login username. Required for ssh/database/redis/mongodb; optional for kafka (only when SASL is configured)."},
				paramSpec{name: "password", typ: "string", desc: "Plaintext password. Stored encrypted by the app. For SSH password auth, database/redis/mongodb, or kafka SASL auth."},
				paramSpec{name: "auth_type", typ: "string", desc: `SSH auth method: "password" (default if password supplied) or "key" (default if private_key supplied). Only for SSH type.`},
				paramSpec{name: "private_key", typ: "string", desc: "SSH private key in PEM format. Imported into the credential store and linked to the asset. SSH only."},
				paramSpec{name: "passphrase", typ: "string", desc: "Passphrase for the SSH private key, if encrypted. SSH only."},
				paramSpec{name: "driver", typ: "string", desc: `Database driver: "mysql" or "postgresql". Required for database type.`},
				paramSpec{name: "database", typ: "string", desc: "Default database name. For database / mongodb type."},
				paramSpec{name: "read_only", typ: "string", desc: `Set to "true" to enable read-only mode. For database type.`},
				paramSpec{name: "redis_db", typ: "number", desc: "Default Redis DB index (0-15). Redis only."},
				paramSpec{name: "kubeconfig", typ: "string", desc: "Kubeconfig YAML content. Required for k8s type."},
				paramSpec{name: "namespace", typ: "string", desc: "Default Kubernetes namespace. K8s only."},
				paramSpec{name: "context", typ: "string", desc: "Kubeconfig context name to use. K8s only."},
				paramSpec{name: "brokers", typ: "string", desc: `Kafka broker list as comma/semicolon/newline separated "host:port" pairs (e.g. "kafka-0:9092,kafka-1:9092"). Kafka only; falls back to host+port when omitted.`},
				paramSpec{name: "client_id", typ: "string", desc: "Kafka client ID label. Kafka only; defaults to opskat."},
				paramSpec{name: "sasl_mechanism", typ: "string", desc: `Kafka SASL mechanism: "none" (default), "plain", "scram-sha-256", "scram-sha-512". Kafka only.`},
				paramSpec{name: "tls", typ: "string", desc: `Set to "true" to enable TLS. Kafka only.`},
				paramSpec{name: "tls_insecure", typ: "string", desc: `Set to "true" to skip TLS certificate verification. Kafka only.`},
				paramSpec{name: "ssh_asset_id", typ: "number", desc: "SSH asset ID for tunnel connection. For database / redis / mongodb / kafka / k8s types."},
				paramSpec{name: "group_id", typ: "number", desc: "Group ID to assign this asset to."},
				paramSpec{name: "description", typ: "string", desc: "Optional description or notes."},
			),
			false,
			handleAddAsset,
		),
		rawTool(
			"update_asset",
			"Update an existing asset. Only provide the fields you want to change; omitted fields remain unchanged. Pass an empty string to clear description / database / icon. Use list_assets + get_asset first to confirm the current state.",
			makeSchema(
				paramSpec{name: "id", typ: "number", required: true, desc: "ID of the asset to update."},
				paramSpec{name: "name", typ: "string", desc: "New display name."},
				paramSpec{name: "host", typ: "string", desc: "New hostname or IP."},
				paramSpec{name: "port", typ: "number", desc: "New port."},
				paramSpec{name: "username", typ: "string", desc: "New username."},
				paramSpec{name: "password", typ: "string", desc: "New password (plaintext). Stored encrypted; switches the asset to inline password auth."},
				paramSpec{name: "auth_type", typ: "string", desc: `SSH auth method: "password" or "key". SSH only.`},
				paramSpec{name: "private_key", typ: "string", desc: "Replace SSH private key (PEM). Re-imports into credential store. SSH only."},
				paramSpec{name: "passphrase", typ: "string", desc: "Passphrase for new SSH private key, if encrypted. SSH only."},
				paramSpec{name: "driver", typ: "string", desc: `Database driver: "mysql" or "postgresql". Database only.`},
				paramSpec{name: "database", typ: "string", desc: "New default database. Database / mongodb only. Pass empty string to clear."},
				paramSpec{name: "read_only", typ: "string", desc: `Set to "true"/"false" to toggle read-only. Database only.`},
				paramSpec{name: "redis_db", typ: "number", desc: "New default Redis DB index. Redis only."},
				paramSpec{name: "brokers", typ: "string", desc: `New Kafka broker list (comma/semicolon/newline separated "host:port"). Kafka only.`},
				paramSpec{name: "client_id", typ: "string", desc: "New Kafka client ID. Kafka only."},
				paramSpec{name: "sasl_mechanism", typ: "string", desc: `New Kafka SASL mechanism: "none", "plain", "scram-sha-256", "scram-sha-512". Kafka only.`},
				paramSpec{name: "tls", typ: "string", desc: `Set to "true"/"false" to toggle Kafka TLS. Kafka only.`},
				paramSpec{name: "tls_insecure", typ: "string", desc: `Set to "true"/"false" to toggle Kafka TLS skip-verify. Kafka only.`},
				paramSpec{name: "ssh_asset_id", typ: "number", desc: "New SSH tunnel asset ID. Pass 0 to detach. Database / redis / mongodb / kafka only."},
				paramSpec{name: "description", typ: "string", desc: "New description. Pass empty string to clear."},
				paramSpec{name: "group_id", typ: "number", desc: "New group ID (must be a positive integer from list_groups). Omit to keep current group; values <= 0 are ignored. To remove an asset from its group, ask the user to do it in the UI."},
				paramSpec{name: "icon", typ: "string", desc: "New icon name."},
			),
			false,
			handleUpdateAsset,
		),
		rawTool(
			"list_groups",
			"List all asset groups. Groups organize assets into a hierarchy via parent_id. Use get_group to view group description.",
			makeSchema(),
			false,
			handleListGroups,
		),
		rawTool(
			"get_group",
			"Get detailed information about a specific asset group, including its description.",
			makeSchema(
				paramSpec{name: "id", typ: "number", required: true, desc: "Group ID. Use list_groups to find available IDs."},
			),
			false,
			handleGetGroup,
		),
		rawTool(
			"add_group",
			"Create a new asset group. Groups can be nested via parent_id to form a hierarchy.",
			makeSchema(
				paramSpec{name: "name", typ: "string", required: true, desc: "Display name for the group."},
				paramSpec{name: "parent_id", typ: "number", desc: "Parent group ID for nesting. Omit or set to 0 for a top-level group."},
				paramSpec{name: "icon", typ: "string", desc: "Optional icon name."},
				paramSpec{name: "description", typ: "string", desc: "Optional description."},
				paramSpec{name: "sort_order", typ: "number", desc: "Sort order within the parent group; lower comes first."},
			),
			false,
			handleAddGroup,
		),
		rawTool(
			"update_group",
			"Update an existing asset group. Only provide the fields you want to change; omitted fields remain unchanged. Pass empty string to clear icon / description.",
			makeSchema(
				paramSpec{name: "id", typ: "number", required: true, desc: "ID of the group to update."},
				paramSpec{name: "name", typ: "string", desc: "New display name."},
				paramSpec{name: "parent_id", typ: "number", desc: "New parent group ID (must be a positive integer from list_groups). Omit to keep current parent; values <= 0 are ignored. To make a group top-level, ask the user to do it in the UI."},
				paramSpec{name: "icon", typ: "string", desc: "New icon name. Empty string clears."},
				paramSpec{name: "description", typ: "string", desc: "New description. Empty string clears."},
				paramSpec{name: "sort_order", typ: "number", desc: "New sort order."},
			),
			false,
			handleUpdateGroup,
		),
	}
}
